<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AmlaForm4a extends Model
{
    //
    protected $table = 'istr_AMLAForm4a';
    protected $primaryKey = 'form_id';
    public $timestamps = false;
    protected $fillable = [
        'form_id',
        'attempted_not_complete',
        'str_reported_due',
        'state_relevant_source',
        'suspect_predicate',
        'red_flag_indicator',
        'description_trans_pattern',
        'details_reasons',
        'related_pep',
        'description_relationship_pep',
        'keyword_report',
        'cust_title',
        'cust_name',
        'cust_name_alias',
        'cust_gender',
        'cust_nationality',
        'cust_nric',
        'cust_passport',
        'cust_other_id',
        'cust_dob',
        'cust_res_address',
        'cust_res_town',
        'cust_res_postcode',
        'cust_res_state',
        'cust_res_nationality',
        'cust_corr_address',
        'cust_corr_town',
        'cust_corr_postcode',
        'cust_corr_state',
        'cust_corr_country',
        'cust_email',
        'cust_phone_country',
        'cust_phone',
        'cust_AML_rating',
        'cust_occu',
        'cust_occu_desc',
        'cust_emp_name',
        'cust_emp_sec',
        'cust_annual_income',
        'cust_marital',
        'cust_spouse_name',
        'cust_spouse_nationality',
        'cust_spouse_nric',
        'cust_spouse_passport',
        'cust_spouse_other_id',
        'cust_spouse_dob',
        'bank_name',
        'bank_acc_no',
        'bank_acc_type',
        'bank_home_branch',
        'sus_trans_producttype',
        'sus_trans_datefrom',
        'sus_trans_dateto',
        'sus_trans_amt_myr',
        'sus_trans_currency',
        'sus_trans_amt_fc',
        'sus_title',
        'sus_name',
        'sus_name_other',
        'sus_gender',
        'sus_nationality',
        'sus_nric',
        'sus_passport',
        'sus_other_id',
        'sus_dob',
        'sus_address',
        'sus_town',
        'sus_postcode',
        'sus_state',
        'sus_country',
        'sus_corr_address',
        'sus_corr_town',
        'sus_corr_postcode',
        'sus_corr_state',
        'sus_corr_country',
        'sus_email',
        'sus_phone_country',
        'sus_phone',
        'sus_occu',
        'sus_relationship',
        'firm_producttype',
        'firm_other',
        'firm_quantity',
        'firm_amt',
        'firm_date',
        'firm_serv',
        'firm_trans_amt',
    ];
}
