<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AmlaForm2 extends Model
{
    //
    protected $table = 'istr_AMLAForm2';
    protected $primaryKey = 'form_id';
    public $timestamps = false;
    protected $fillable = [
        'form_id',
        'branch_name',
        'cust_name',
        'date',
        'contact',
        'sales_name',
        'total_mark',
        'risk_rating',
        'cust_type',
        'individual',
        'legal_clubs',
        'legal_arrangement',
        'non_pep',
        'local_pep',
        'foreign_pep',
        'high_net_worth_no_low',
        'high_net_worth_yes_high',
        'high_net_worth_comments',
        'nric_passport',
        'businessSize_small_low',
        'businessSize_large_high',
        'businessSize_comments',
        'businessType_lowrisk_low',
        'businessType_highrisk_high',
        'CDD_clear_low',
        'CDD_vague_high',
        'beneficial_no_low',
        'beneficial_yes_high',
        'trade_no_low',
        'trade_yes_high',
        'remark_no_low',
        'remark_yes_high',
        'yes_state',
        'originCountry_lowrisk_low',
        'originCountry_taxhaven_medium',
        'originCountry_FATF_high',
        'countryResidence_lowrisk_low',
        'countryResidence_taxhaven_medium',
        'countryResidence_FATF_high',
        'product_nongold_low',
        'product_diamondgem_medium',
        'product_gold_high',
        'delivery_face2face_low',
        'delivery_behalf_medium',
        'delivery_non_face2face_high',
        'payment_electronic_low',
        'payment_cash_medium',
        'payment_cash_high',
        'transaction_fundFrom_local_low',
        'transaction_fundFrom_foreign_medium',
        'transaction_fundFrom_high',
        'transaction_fundFrom_known_low',
        'transaction_fundFrom_unrelated_high',
        'transaction_fundTrans_local_low',
        'transaction_fundTrans_foreign_medium',
        'transaction_fundTrans_highrisk_high',
        'transaction_fundTrans_known_low',
        'transaction_fundTrans_unrelated_high',
        'individual_minusCash',
        'individual_minusCash_percentage',
        'nonindividual_minusCash',
        'nonindividual_minusCash_percentage',
        'individual_minusnonCash',
        'individual_minusnonCash_percentage',
        'nonindividual_minusnonCash',
        'nonindividual_minusnonCash_percentage',
        'riskrating',
        'riskrating_transaction',
        'is_cust_sus',
        'cust_sus_reason',
        'is_cust_info_complete',
        'is_internal_str_required',
        'conclusion_comment',
        'prepared_name',
        'prepared_designation',
        'prepared_date',
        'reviewed_name',
        'reviewed_designation',
        'reviewed_date',
        'prepared_signature',
        'reviewed_signature',

    ];
}
